CREATE SEQUENCE IF NOT EXISTS categories_id_seq INCREMENT BY 1 START WITH 101 OWNED BY categories.id;

CREATE SEQUENCE IF NOT EXISTS descriptions_id_seq INCREMENT BY 1 START WITH 101 OWNED BY descriptions.id;

CREATE SEQUENCE IF NOT EXISTS products_id_seq INCREMENT BY 1 START WITH 101 OWNED BY products.id;