CREATE SEQUENCE IF NOT EXISTS users_id_seq INCREMENT BY 25 START WITH 101 OWNED BY users.id;

CREATE SEQUENCE IF NOT EXISTS roles_id_seq INCREMENT BY 1 START WITH 101 OWNED BY roles.id;

CREATE SEQUENCE IF NOT EXISTS tokens_id_seq INCREMENT BY 25 START WITH 101 OWNED BY tokens.id;